before_script: 
  - gem install bundler
  - bundle update rake
  - gem update --system
  - cat config/database.yml
  - rails db:migrate RAILS_ENV=test
language: ruby
rvm:
- 2.6.5
env:
- DB=postgresql
